m4_define(`m4_SSH_ASKPASS_DEFAULT_NOTIFY_COMMAND', `notify-send -t 5000')m4_dnl
m4_define(`m4_SSH_ASKPASS_NOTIFY_ENV', `F2HS_SSH_ASKPASS_NOTIFY')m4_dnl
m4_define(`m4_SSH_ASKPASS_ENCRYPTED_KEYFILE_ENV', `F2HS_SSH_ASKPASS_KEYFILE')m4_dnl
m4_define(`m4_SSH_ASKPASS_DEFAULT_ENCRYPTED_KEYFILE', `$HOME/.ssh/'m4_APPNAME`-askpass-keyfile')m4_dnl
m4_define(`m4_INITCPIO_DEFAULT_MAX_PASSPHRASE_ATTEMPTS', `3')m4_dnl
m4_define(`m4_INITCPIO_DEFAULT_ENCRYPTED_KEYFILE_DIR', `/keyfiles')m4_dnl
m4_define(`m4_INITCPIO_DEFAULT_KEYFILES_SOURCE_DIR', `/boot/keyfiles')m4_dnl
